name: Mongolia News Monitor

permissions:
  contents: write

on:
  schedule:
    - cron: '0 4 * * *'
    - cron: '0 10 * * *'
    - cron: '0 13 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Show Python Version
        run: |
          python --version

      - name: Install Packages
        run: |
          pip install feedparser

      - name: Test RSS Fetcher
        run: |
          python scripts/rss_fetcher.py

      - name: Build HTML
        run: |
          python scripts/build_html.py

      - name: Commit Generated Files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add docs/

          git diff --cached --quiet || git commit -m "Auto update news page"

          git push

      - name: Workflow Ready
        run: |
          echo "Mongolia News Monitor Initialized"
